### ISSUE TITLE
Help for getting ScientificPython on OSX

### ISSUE THREAD

**Issue by jbryson3** [szcom/rnnlib#7]
On OSX Yosemite, I'm trying to run build/examples/online_prediction/build_netcdf.sh. I'm running into problems with the ScientificPython. 

The latest ScientificPython binary on osx require python 2.4. That python is so old that pyenv is having trouble building it.

So I tried build the latest development ScientificPython (2.9.4) with the python I have installed 2.7.11. Other than spitting out a ton of unused function warnings, the build seems to have succeeded. However, when I attempt to run build_netcdf, this is what I get:

> ./build_netcdf.sh
```
Traceback (most recent call last):
  File "./online_delta.py", line 3, in <module>
    import netcdf_helpers
  File "/Users/jbryson3/code/libs/rnnlib/utils/netcdf_helpers.py", line 18, in <module>
    from Scientific.IO.NetCDF import NetCDFFile
  File "/usr/local/lib/python2.7/site-packages/Scientific/IO/NetCDF.py", line 168, in <module>
    from Scientific._netcdf import *
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/Scientific/_netcdf.so, 2): Symbol not found: _H5P_CLS_DATASET_ACCESS_ID_g
  Referenced from: /usr/local/lib/python2.7/site-packages/Scientific/_netcdf.so
  Expected in: flat namespace
 in /usr/local/lib/python2.7/site-packages/Scientific/_netcdf.so
```

I realize this may be a bit out of scope for this codebase, but was hoping someone could point me in the right direction. Thanks!

**Comment by aferriss** [comment]
I just went through this as well. Instead of downloading the mac binaries, just get the most recent development release tar file and do as their instructions say for the [basic installation](http://dirac.cnrs-orleans.fr/plone/software/scientificpython/installation-instructions/). 

I also had an issue during the install phase where I had to run my mac in recovery mode (cmd + R on bootup) and then enter the terminal and do `csrutil disable` followed by a `reboot`

**Comment by akshaypardeshi26** [comment]
@ jbryson3 I am facing the same issue. Were you able to resolve it?If yes, could you please tell how?
Thanks.

**Comment by jbryson3** [comment]
I was unable to resolve this issue on OSX. Instead I booted up a Ubuntu VM using Virtualbox and was successful after 3-4 days of slow going. I have since removed the vm, so I can't remember the exact steps that I used to get it up an running but before I deleted it, I exported a list of things that I had installed on the box to get it working. Hope it helps.
[dpkglist.txt](https://github.com/szcom/rnnlib/files/299145/dpkglist.txt)
[piplist.txt](https://github.com/szcom/rnnlib/files/299146/piplist.txt)

**Comment by chensg1919** [comment]
I'm facing the same issue,  too. But when I use the VM, I can't solve this problem. Could you tell me how I can handle it ? @jbryson3
